# Site settings
title: Braden Ganetsky
url: https://ganets.ky/
description: "Personal website for Braden Ganetsky."
keywords: "braden, ganetsky, twisty, puzzle, twistypuzzle, tp, rubik, rubik's, cube, 3d, print, printing, geometry, shape, shapes, design, designs, code, c, c++, programming, software, develop, development"
skills: "Puzzle Designer · Software Developer · Public Speaker"
meta_author: Braden Ganetsky
have_xml_feed: false

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 696969 #80B3FF
  primary-rgb: "105,105,105" #"128,179,255"
  secondary: 303030 #FD6E8A
  secondary-rgb: "48,48,48"
  secondary-dark: 202020 #A2122F

header:
  color-group: color-group-1
section_about:
  full_title: About Me
  short_title: About
  color-group: color-group-2
section_puzzles:
  full_title: Twisty Puzzles
  short_title: Puzzles
  color-group: color-group-2
section_speaking:
  full_title: Speaking
  short_title: Speaking
  color-group: color-group-2
section_software:
  full_title: Software Projects
  short_title: Software
  color-group: color-group-2
section_contact:
  full_title: Contact Me
  short_title: Contact
  color-group: color-group-1

# Footer settings
footer:
  copyright: Braden Ganetsky
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/braden-ganetsky/
  - title: youtube
    url: https://www.youtube.com/@k3DW/
  - title: github
    url: https://github.com/k3DW/

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

collections:
  posts_puzzles:
    output: true
  posts_speaking:
    output: true
  posts_software:
    output: true
